In [4]:
from TS_DataLoader import load_from_tsfile_to_dataframe
import os
import pandas as pd

data_dir = 'datasets/Monash_UEA_UCR_Regression_Archive/AppliancesEnergy/AppliancesEnergy_TEST.ts'
# data_dir = 'datasets/Monash_UEA_UCR_Regression_Archive/AustraliaRainfall/AustraliaRainfall_TEST.ts'
# 使用os.path.basename()从路径中提取文件名（包括扩展名）
file_with_extension = os.path.basename(data_dir)

# 分割字符串并获取不包含扩展名的文件名部分
result_name = file_with_extension.split('.')[0]
data= load_from_tsfile_to_dataframe(data_dir,False)

# df = pd.DataFrame(data)

# print(data.head())

#
# print(data[0])

66it [00:01, 57.41it/s]

In [6]:
# data[0]
data

,dim_0,dim_1,dim_2,dim_3,dim_4,dim_5,dim_6,dim_7,dim_8,dim_9,...,dim_15,dim_16,dim_17,dim_18,dim_19,dim_20,dim_21,dim_22,dim_23,class_vals
0,2016-03-25 17:00:00 22.60 2016-03-25 17:10:...,2016-03-25 17:00:00 40.260000 2016-03-25 17...,2016-03-25 17:00:00 20.323333 2016-03-25 17...,2016-03-25 17:00:00 43.200000 2016-03-25 17...,2016-03-25 17:00:00 24.566667 2016-03-25 17...,2016-03-25 17:00:00 38.530000 2016-03-25 17...,2016-03-25 17:00:00 20.10 2016-03-25 17:10:...,2016-03-25 17:00:00 37.363333 2016-03-25 17...,2016-03-25 17:00:00 19.426667 2016-03-25 17...,2016-03-25 17:00:00 48.126667 2016-03-25 17...,...,2016-03-25 17:00:00 40.290000 2016-03-25 17...,2016-03-25 17:00:00 19.79 2016-03-25 17:10:...,2016-03-25 17:00:00 41.966667 2016-03-25 17...,2016-03-25 17:00:00 10.400000 2016-03-25 17...,2016-03-25 17:00:00 757.000000 2016-03-25 1...,2016-03-25 17:00:00 66.000000 2016-03-25 17...,2016-03-25 17:00:00 4.000000 2016-03-25 17:...,2016-03-25 17:00:00 40.0 2016-03-25 17:10:0...,2016-03-25 17:00:00 4.200000 2016-03-25 17:...,17.37
1,2016-03-15 17:00:00 21.390000 2016-03-15 17...,2016-03-15 17:00:00 34.266667 2016-03-15 17...,2016-03-15 17:00:00 20.133333 2016-03-15 17...,2016-03-15 17:00:00 34.463333 2016-03-15 17...,2016-03-15 17:00:00 20.790000 2016-03-15 17...,2016-03-15 17:00:00 34.845000 2016-03-15 17...,2016-03-15 17:00:00 21.000000 2016-03-15 17...,2016-03-15 17:00:00 33.200000 2016-03-15 17...,2016-03-15 17:00:00 19.390000 2016-03-15 17...,2016-03-15 17:00:00 42.566667 2016-03-15 17...,...,2016-03-15 17:00:00 33.230000 2016-03-15 17...,2016-03-15 17:00:00 19.79 2016-03-15 17:10:...,2016-03-15 17:00:00 37.760000 2016-03-15 17...,2016-03-15 17:00:00 9.600000 2016-03-15 17:...,2016-03-15 17:00:00 763.600000 2016-03-15 1...,2016-03-15 17:00:00 71.000000 2016-03-15 17...,2016-03-15 17:00:00 6.000000 2016-03-15 17:...,2016-03-15 17:00:00 20.000000 2016-03-15 17...,2016-03-15 17:00:00 4.500000 2016-03-15 17:...,20.65
2,2016-01-17 17:00:00 21.700000 2016-01-17 17...,2016-01-17 17:00:00 35.590000 2016-01-17 17...,2016-01-17 17:00:00 20.290 2016-01-17 17:10...,2016-01-17 17:00:00 35.975000 2016-01-17 17...,2016-01-17 17:00:00 21.000000 2016-01-17 17...,2016-01-17 17:00:00 37.060000 2016-01-17 17...,2016-01-17 17:00:00 20.890000 2016-01-17 17...,2016-01-17 17:00:00 36.100000 2016-01-17 17...,2016-01-17 17:00:00 18.00 2016-01-17 17:10:...,2016-01-17 17:00:00 46.090000 2016-01-17 17...,...,2016-01-17 17:00:00 37.222500 2016-01-17 17...,2016-01-17 17:00:00 18.1 2016-01-17 17:10:0...,2016-01-17 17:00:00 37.030000 2016-01-17 17...,2016-01-17 17:00:00 0.800000 2016-01-17 17:...,2016-01-17 17:00:00 764.900000 2016-01-17 1...,2016-01-17 17:00:00 73.000000 2016-01-17 17...,2016-01-17 17:00:00 2.0 2016-01-17 17:10:00...,2016-01-17 17:00:00 40.000000 2016-01-17 17...,2016-01-17 17:00:00 -3.600000 2016-01-17 17:...,11.42
3,2016-04-11 17:00:00 22.500000 2016-04-11 17...,2016-04-11 17:00:00 41.163333 2016-04-11 17...,2016-04-11 17:00:00 22.500000 2016-04-11 17...,2016-04-11 17:00:00 38.966667 2016-04-11 17...,2016-04-11 17:00:00 23.200000 2016-04-11 17...,2016-04-11 17:00:00 38.863333 2016-04-11 17...,2016-04-11 17:00:00 22.1 2016-04-11 17:10:0...,2016-04-11 17:00:00 40.363333 2016-04-11 17...,2016-04-11 17:00:00 21.000000 2016-04-11 17...,2016-04-11 17:00:00 44.700000 2016-04-11 17...,...,2016-04-11 17:00:00 42.090000 2016-04-11 17...,2016-04-11 17:00:00 20.963333 2016-04-11 17...,2016-04-11 17:00:00 41.363333 2016-04-11 17...,2016-04-11 17:00:00 15.300000 2016-04-11 17...,2016-04-11 17:00:00 750.600000 2016-04-11 1...,2016-04-11 17:00:00 66.000000 2016-04-11 17...,2016-04-11 17:00:00 4.000000 2016-04-11 17:...,2016-04-11 17:00:00 40.0 2016-04-11 17:10:0...,2016-04-11 17:00:00 9.000000 2016-04-11 17:...,10.68
4,2016-04-13 17:00:00 22.000000 2016-04-13 17...,2016-04-13 17:00:00 42.900000 2016-04-13 17...,2016-04-13 17:00:00 20.566667 2016-04-13 17...,2016-04-13 17:00:00 44.030000 2016-04-13 17...,2016-04-13 17:00:00 23.200000 2016-04-13 17...,2016-04-13 17:00:00 39.290000 2016-04-13 17...,2016-04-13 17:00:00 22.230000 2016-04-13 17...,2016-04-13 17:00:00 41.390000 2016-04-13 17...,2016-04-13 17:00:00 20.79 2016-04-13 17:10:...,2016-04-13 17:00:00 45.152857 2016-04-13 17...,...,2016-04-13 17:00:00 43.826667 2016-04-13 17...,2016-04-13 17:00:00 20.5 2016-04-13 17:10:0...,2016-04-13 17:00:00 42.790000 2016-04-13 17...,2016-04-13 17:00:00 10.000000 2016-04-13 17...,2016-04-13 17:00:00 752.100000 2016-04-13 1...,2016-04-13 17:00:00 92.0 2016-04-13 17:10:0...,2016-04-13 17:00:00 1.000000 2016-04-13 17:...,2016-04-13 17:00:00 22.000000 2016-04-13 17...,2016-04-13 17:00:00 8.700000 2016-04-13 17:...,12.44
5,2016-04-26 17:00:00 20.890000 2016-04-26 17...,2016-04-26 17:00:00 37.290000 2016-04-26 17...,2016-04-26 17:00:00 19.500000 2016-04-26 17...,2016-04-26 17:00:00 37.790000 2016-04-26 17...,2016-04-26 17:00:00 21.700000 2016-04-26 17...,2016-04-26 17:00:00 35.000000 2016-04-26 17...,2016-04-26 17:00:00 20.600000 2016-04-26 17...,2016-04-26 17:00:00 34.500000 2016-04-26 17...,2016-04-26 17:00:00 19.390000 2016-04-26 17...,2016-04-26 17:00:00 43.200000 2016-04-26 17...,...,2016-04-26 17:00:00 38.126667 2016-04-26 17...,2016-04-26 17:00:00 19.5 2016-04-26 17:10:0...,2016-04-26 17:00:00 34.790000 2016-04-26 17...,2016-04-26 17:00:00 5.000000 2016-04-26 17:...,2016-04-26 17:00:00 748.600000 2016-04-26 1...,2016-04-26 17:00:00 75.000000 2016-04-26 17...,2016-04-26 17:00:00 6.000000 2016-04-26 17:...,2016-04-26 17:00:00 40.0 2016-04-26 17:10:0...,2016-04-26 17:00:00 0.800000 2016-04-26 17:...,11.17
6,2016-04-21 17:00:00 23.000000 2016-04-21 17...,2016-04-21 17:00:00 34.933333 2016-04-21 17...,2016-04-21 17:00:00 23.100000 2016-04-21 17...,2016-04-21 17:00:00 32.760000 2016-04-21 17...,2016-04-21 17:00:00 23.100000 2016-04-21 17...,2016-04-21 17:00:00 35.433333 2016-04-21 17...,2016-04-21 17:00:00 22.890000 2016-04-21 17...,2016-04-21 17:00:00 33.900000 2016-04-21 17...,2016-04-21 17:00:00 21.000 2016-04-21 17:10...,2016-04-21 17:00:00 38.200000 2016-04-21 17...,...,2016-04-21 17:00:00 38.400000 2016-04-21 17...,2016-04-21 17:00:00 20.200000 2016-04-21 17...,2016-04-21 17:00:00 36.200000 2016-04-21 17...,2016-04-21 17:00:00 18.50 2016-04-21 17:10:...,2016-04-21 17:00:00 759.900000 2016-04-21 1...,2016-04-21 17:00:00 37.000000 2016-04-21 17...,2016-04-21 17:00:00 4.0 2016-04-21 17:10:00...,2016-04-21 17:00:00 40.000000 2016-04-21 17...,2016-04-21 17:00:00 3.30 2016-04-21 17:10:0...,24.12
7,2016-02-20 17:00:00 22.600000 2016-02-20 17...,2016-02-20 17:00:00 39.900000 2016-02-20 17...,2016-02-20 17:00:00 21.790000 2016-02-20 17...,2016-02-20 17:00:00 39.730000 2016-02-20 17...,2016-02-20 17:00:00 22.042857 2016-02-20 17...,2016-02-20 17:00:00 40.121429 2016-02-20 17...,2016-02-20 17:00:00 18.390000 2016-02-20 17...,2016-02-20 17:00:00 46.530000 2016-02-20 17...,2016-02-20 17:00:00 17.700000 2016-02-20 17...,2016-02-20 17:00:00 52.290000 2016-02-20 17...,...,2016-02-20 17:00:00 49.030000 2016-02-20 17...,2016-02-20 17:00:00 17.79 2016-02-20 17:10:...,2016-02-20 17:00:00 44.290000 2016-02-20 17...,2016-02-20 17:00:00 9.6 2016-02-20 17:10:0...,2016-02-20 17:00:00 754.00 2016-02-20 17:10...,2016-02-20 17:00:00 92.000000 2016-02-20 17...,2016-02-20 17:00:00 8.000000 2016-02-20 17...,2016-02-20 17:00:00 40.0 2016-02-20 17:10:0...,2016-02-20 17:00:00 8.300000 2016-02-20 17:...,10.99
8,2016-03-02 17:00:00 21.000000 2016-03-02 17...,2016-03-02 17:00:00 36.760000 2016-03-02 17...,2016-03-02 17:00:00 19.700000 2016-03-02 17...,2016-03-02 17:00:00 36.500000 2016-03-02 17...,2016-03-02 17:00:00 20.500000 2016-03-02 17...,2016-03-02 17:00:00 37.290000 2016-03-02 17...,2016-03-02 17:00:00 20.100000 2016-03-02 17...,2016-03-02 17:00:00 35.200000 2016-03-02 17...,2016-03-02 17:00:00 18.066667 2016-03-02 17...,2016-03-02 17:00:00 44.966667 2016-03-02 17...,...,2016-03-02 17:00:00 40.266667 2016-03-02 17...,2016-03-02 17:00:00 18.390000 2016-03-02 17...,2016-03-02 17:00:00 41.433333 2016-03-02 17...,2016-03-02 17:00:00 4.000000 2016-03-02 17:...,2016-03-02 17:00:00 742.500000 2016-03-02 1...,2016-03-02 17:00:00 86.000000 2016-03-02 17...,2016-03-02 17:00:00 8.000000 2016-03-02 17:...,2016-03-02 17:00:00 40.0 2016-03-02 17:10:0...,2016-03-02 17:00:00 1.800000 2016-03-02 17:...,13.76
9,2016-02-09 17:00:00 22.290000 2016-02-09 17...,2016-02-09 17:00:00 42.800000 2016-02-09 17...,2016-02-09 17:00:00 21.89 2016-02-09 17:10:...,2016-02-09 17:00:00 40.663333 2016-02-09 17...,2016-02-09 17:00:00 22.500000 2016-02-09 17...,2016-02-09 17:00:00 41.966667 2016-02-09 17...,2016-02-09 17:00:00 19.500000 2016-02-09 17...,2016-02-09 17:00:00 41.000000 2016-02-09 17...,2016-02-09 17:00:00 19.600000 2016-02-09 17...,2016-02-09 17:00:00 49.200000 2016-02-09 17...,...,2016-02-09 17:00:00 44.411111 2016-02-09 17...,2016-02-09 17:00:00 19.0 2016-02-09 17:10:0...,2016-02-09 17:00:00 43.290000 2016-02-09 17...,2016-02-09 17:00:00 4.100000 2016-02-09 17:...,2016-02-09 17:00:00 734.300000 2016-02-09 1...,2016-02-09 17:00:00 91.000000 2016-02-09 17...,2016-02-09 17:00:00 6.000000 2016-02-09 17:...,2016-02-09 17:00:00 28.0 2016-02-09 17:10:0...,2016-02-09 17:00:00 2.700000 2016-02-09 17:...,14.56
10,2016-03-19 17:00:00 21.200000 2016-03-19 17...,2016-03-19 17:00:00 35.930000 2016-03-19 17...,2016-03-19 17:00:00 19.200000 2016-03-19 17...,2016-03-19 17:00:00 37.466667 2016-03-19 17...,2016-03-19 17:00:00 22.260 2016-03-19 17:10...,2016-03-19 17:00:00 34.400000 2016-03-19 17...,2016-03-19 17:00:00 20.890000 2016-03-19 17...,2016-03-19 17:00:00 35.126667 2016-03-19 17...,2016-03-19 17:00:00 18.500000 2016-03-19 17...,2016-03-19 17:00:00 43.500000 2016-03-19 17...,...,2016-03-19 17:00:00 36.700000 2016-03-19 17...,2016-03-19 17:00:00 19.39 2016-03-19 17:10:...,2016-03-19 17:00:00 35.200000 2016-03-19 17...,2016-03-19 17:00:00 7.100000 2016-03-19 17:...,2016-03-19 17:00:00 762.100000 2016-03-19 1...,2016-03-19 17:00:00 68.0 2016-03-19 17:10:0...,2016-03-19 17:00:00 3.000000 2016-03-19 17:...,2016-03-19 17:00:00 29.000000 2016-03-19 17...,2016-03-19 17:00:00 1.600000 2016-03-19 17:...,14.97
11,2016-02-22 17:00:00 21.00 2016-02-22 17:10:...,2016-02-22 17:00:00 45.626667 2016-02-22 17...,2016-02-22 17:00:00 19.700000 2016-02-22 17...,2016-02-22 17:00:00 45.966667 2016-02-22 17...,2016-02-22 17:00:00 21.600000 2016-02-22 17...,2016-02-22 17:00:00 42.730000 2016-02-22 17...,2016-02-22 17:00:00 20.100000 2016-02-22 17...,2016-02-22 17:00:00 44.933333 2016-02-22 17...,2016-02-22 17:00:00 18.500000 2016-02-22 17...,2016-02-22 17:00:00 53.168571 2016-02-22 17...,...,2016-02-22 17:00:00 48.333333 2016-02-22 17...,2016-02-22 17:00:00 18.700000 2016-02-22 17...,2016-02-22 17:00:00 46.948750 2016-02-22 17...,2016-02-22 17:00:00 6.100000 2016-02-22 17:...,2016-02-22 17:00:00 751.400000 2016-02-22 1...,2016-02-22 17:00:00 97.000000 2016-02-22 17...,2016-02-22 17:00:00 6.000000 2016-02-22 17:...,2016-02-22 17:00:00 61.000000 2016-02-22 17...,2016-02-22 17:00:00 5.700000 2016-02-22 17:...,13.43
12,2016-04-06 17:00:00 21.790000 2016-04-06 17...,2016-04-06 17:00:00 42.230000 2016-04-06 17...,2016-04-06 17:00:00 20.290000 2016-04-06 17...,2016-04-06 17:00:00 43.326667 2016-04-06 17...,2016-04-06 17:00:00 22.700000 2016-04-06 17...,2016-04-06 17:00:00 38.760000 2016-04-06 17...,2016-04-06 17:00:00 21.290000 2016-04-06 17...,2016-04-06 17:00:00 41.060000 2016-04-06 17...,2016-04-06 17:00:00 20.500000 2016-04-06 17...,2016-04-06 17:00:00 45.790000 2016-04-06 17...,...,2016-04-06 17:00:00 43.363333 2016-04-06 17...,2016-04-06 17:00:00 20.790000 2016-04-06 17...,2016-04-06 17:00:00 39.760000 2016-04-06 17...,2016-04-06 17:00:00 11.300000 2016-04-06 17...,2016-04-06 17:00:00 751.200000 2016-04-06 1...,2016-04-06 17:00:00 79.000000 2016-04-06 17...,2016-04-06 17:00:00 7.000000 2016-04-06 17:...,2016-04-06 17:00:00 40.000000 2016-04-06 17...,2016-04-06 17:00:00 7.800000 2016-04-06 17:...,11.57
13,2016-05-11 17:00:00 25.463333 2016-05-11 17...,2016-05-11 17:00:00 50.530000 2016-05-11 17...,2016-05-11 17:00:00 25.451429 2016-05-11 17...,2016-05-11 17:00:00 48.637143 2016-05-11 17...,2016-05-11 17:00:00 26.175000 2016-05-11 17...,2016-05-11 17:00:00 45.855000 2016-05-11 17...,2016-05-11 17:00:00 26.000000 2016-05-11 17...,2016-05-11 17:00:00 46.621429 2016-05-11 17...,2016-05-11 17:00:00 24.066667 2016-05-11 17...,2016-05-11 17:00:00 52.333333 2016-05-11 17...,...,2016-05-11 17:00:00 49.526667 2016-05-11 17...,2016-05-11 17:00:00 24.100000 2016-05-11 17...,2016-05-11 17:00:00 48.076000 2016-05-11 17...,2016-05-11 17:00:00 22.700000 2016-05-11 17...,2016-05-11 17:00:00 746.600000 2016-05-11 1...,2016-05-11 17:00:00 56.000000 2016-05-11 17...,2016-05-11 17:00:00 2.000000 2016-05-11 17:...,2016-05-11 17:00:00 40.000000 2016-05-11 17...,2016-05-11 17:00:00 13.40 2016-05-11 17:10:...,9.33
14,2016-04-16 17:00:00 22.666667 2016-04-16 17...,2016-04-16 17:00:00 57.496667 2016-04-16 17...,2016-04-16 17:00:00 21.290000 2016-04-16 17...,2016-04-16 17:00:00 56.026667 2016-04-16 17...,2016-04-16 17:00:00 24.890000 2016-04-16 17...,2016-04-16 17:00:00 40.490000 2016-04-16 17...,2016-04-16 17:00:00 21.890000 2016-04-16 17...,2016-04-16 17:00:00 38.590000 2016-04-16 17...,2016-04-16 17:00:00 20.890000 2016-04-16 17...,2016-04-16 17:00:00 49.293333 2016-04-16 17...,...,2016-04-16 17:00:00 41.700000 2016-04-16 17...,2016-04-16 17:00:00 21.1 2016-04-16 17:10:0...,2016-04-16 17:00:00 43.200000 2016-04-16 17...,2016-04-16 17:00:00 7.600000 2016-04-16 17:...,2016-04-16 17:00:00 748.300000 2016-04-16 1...,2016-04-16 17:00:00 87.000000 2016-04-16 17...,2016-04-16 17:00:00 3.000000 2016-04-16 17:...,2016-04-16 17:00:00 40.0 2016-04-16 17:10:0...,2016-04-16 17:00:00 5.600000 2016-04-16 17:...,15.58
15,2016-03-13 17:00:00 22.290000 2016-03-13 17...,2016-03-13 17:00:00 33.863333 2016-03-13 17...,2016-03-13 17:00:00 20.500000 2016-03-13 17...,2016-03-13 17:00:00 34.400000 2016-03-13 17...,2016-03-13 17:00:00 20.730000 2016-03-13 17...,2016-03-13 17:00:00 35.500000 2016-03-13 17...,2016-03-13 17:00:00 20.890000 2016-03-13 17...,2016-03-13 17:00:00 33.090000 2016-03-13 17...,2016-03-13 17:00:00 18.100000 2016-03-13 17...,2016-03-13 17:00:00 44.000000 2016-03-13 17...,...,2016-03-13 17:00:00 31.066667 2016-03-13 17...,2016-03-13 17:00:00 19.39 2016-03-13 17:10:...,2016-03-13 17:00:00 37.900000 2016-03-13 17...,2016-03-13 17:00:00 9.600000 2016-03-13 17:...,2016-03-13 17:00:00 768.200000 2016-03-13 1...,2016-03-13 17:00:00 57.000000 2016-03-13 17...,2016-03-13 17:00:00 6.0 2016-03-13 17:10:00...,2016-03-13 17:00:00 28.000000 2016-03-13 17...,2016-03-13 17:00:00 1.300000 2016-03-13 17:...,20.93
16,2016-04-30 17:00:00 22.033333 2016-04-30 17...,2016-04-30 17:00:00 43.360000 2016-04-30 17...,2016-04-30 17:00:00 20.89 2016-04-30 17:10:...,2016-04-30 17:00:00 42.126667 2016-04-30 17...,2016-04-30 17:00:00 23.600000 2016-04-30 17...,2016-04-30 17:00:00 35.826667 2016-04-30 17...,2016-04-30 17:00:00 20.20 2016-04-30 17:10:...,2016-04-30 17:00:00 38.367500 2016-04-30 17...,2016-04-30 17:00:00 19.7 2016-04-30 17:10:0...,2016-04-30 17:00:00 50.633333 2016-04-30 17...,...,2016-04-30 17:00:00 38.000000 2016-04-30 17...,2016-04-30 17:00:00 19.463333 2016-04-30 17...,2016-04-30 17:00:00 37.863333 2016-04-30 17...,2016-04-30 17:00:00 10.500000 2016-04-30 17...,2016-04-30 17:00:00 760.000000 2016-04-30 1...,2016-04-30 17:00:00 64.000000 2016-04-30 17...,2016-04-30 17:00:00 6.000000 2016-04-30 17:...,2016-04-30 17:00:00 40.0 2016-04-30 17:10:0...,2016-04-30 17:00:00 4.000000 2016-04-30 17:...,11.99
17,2016-04-05 17:00:00 22.390000 2016-04-05 17...,2016-04-05 17:00:00 40.930000 2016-04-05 17...,2016-04-05 17:00:00 21.133333 2016-04-05 17...,2016-04-05 17:00:00 41.500000 2016-04-05 17...,2016-04-05 17:00:00 23.890000 2016-04-05 17...,2016-04-05 17:00:00 36.826667 2016-04-05 17...,2016-04-05 17:00:00 21.290000 2016-04-05 17...,2016-04-05 17:00:00 40.230000 2016-04-05 17...,2016-04-05 17:00:00 20.70 2016-04-05 17:10:...,2016-04-05 17:00:00 46.900000 2016-04-05 17...,...,2016-04-05 17:00:00 39.700000 2016-04-05 17...,2016-04-05 17:00:00 20.926667 2016-04-05 17...,2016-04-05 17:00:00 42.530000 2016-04-05 17...,2016-04-05 17:00:00 13.100000 2016-04-05 17...,2016-04-05 17:00:00 751.600000 2016-04-05 1...,2016-04-05 17:00:00 65.000000 2016-04-05 17...,2016-04-05 17:00:00 5.000000 2016-04-05 17:...,2016-04-05 17:00:00 40.0 2016-04-05 17:10:0...,2016-04-05 17:00:00 6.500000 2016-04-05 17:...,15.37
18,2016-04-24 17:00:00 22.100000 2016-04-24 17...,2016-04-24 17:00:00 36.163333 2016-04-24 17...,2016-04-24 17:00:00 20.066667 2016-04-24 17...,2016-04-24 17:00:00 37.590000 2016-04-24 17...,2016-04-24 17:00:00 22.700000 2016-04-24 17...,2016-04-24 17:00:00 34.500000 2016-04-24 17...,2016-04-24 17:00:00 21.600000 2016-04-24 17...,2016-04-24 17:00:00 34.200000 2016-04-24 17...,2016-04-24 17:00:00 20.500000 2016-04-24 17...,2016-04-24 17:00:00 44.490000 2016-04-24 17...,...,2016-04-24 17:00:00 36.090000 2016-04-24 17...,2016-04-24 17:00:00 20.50 2016-04-24 17:10:...,2016-04-24 17:00:00 36.933333 2016-04-24 17...,2016-04-24 17:00:00 5.600000 2016-04-24 17:...,2016-04-24 17:00:00 757.400000 2016-04-24 1...,2016-04-24 17:00:00 79.000000 2016-04-24 17...,2016-04-24 17:00:00 6.000000 2016-04-24 17:...,2016-04-24 17:00:00 40.000000 2016-04-24 17...,2016-04-24 17:00:00 2.200000 2016-04-24 17:...,10.47
19,2016-03-28 17:00:00 23.70 2016-03-28 17:10:...,2016-03-28 17:00:00 41.360000 2016-03-28 17...,2016-03-28 17:00:00 22.533333 2016-03-28 17...,2016-03-28 17:00:00 39.193333 2016-03-28 17...,2016-03-28 17:00:00 24.000000 2016-03-28 17...,2016-03-28 17:00:00 39.656667 2016-03-28 17...,2016-03-28 17:00:00 21.600000 2016-03-28 17...,2016-03-28 17:00:00 39.790000 2016-03-28 17...,2016-03-28 17:00:00 20.29 2016-03-28 17:10:...,2016-03-28 17:00:00 46.760000 2016-03-28 17...,...,2016-03-28 17:00:00 36.000000 2016-03-28 17...,2016-03-28 17:00:00 20.500000 2016-03-28 17...,2016-03-28 17:00:00 41.560000 2016-03-28 17...,2016-03-28 17:00:00 8.300000 2016-03-28 17...,2016-03-28 17:00:00 743.300000 2016-03-28 1...,2016-03-28 17:00:00 78.000000 2016-03-28 17...,2016-03-28 17:00:00 9.000000 2016-03-28 17:...,2016-03-28 17:00:00 40.000000 2016-03-28 17...,2016-03-28 17:00:00 4.60 2016-03-28 17:10:0...,14.41
20,2016-04-17 17:00:00 23.000000 2016-04-17 17...,2016-04-17 17:00:00 41.666667 2016-04-17 17...,2016-04-17 17:00:00 21.100000 2016-04-17 17...,2016-04-17 17:00:00 39.090000 2016-04-17 17...,2016-04-17 17:00:00 22.790000 2016-04-17 17...,2016-04-17 17:00:00 37.030000 2016-04-17 17...,2016-04-17 17:00:00 22.540000 2016-04-17 17...,2016-04-17 17:00:00 36.536000 2016-04-17 17...,2016-04-17 17:00:00 20.790000 2016-04-17 17...,2016-04-17 17:00:00 46.363333 2016-04-17 17...,...,2016-04-17 17:00:00 38.363333 2016-04-17 17...,2016-04-17 17:00:00 21.000000 2016-04-17 17...,2016-04-17 17:00:00 39.790000 2016-04-17 17...,2016-04-17 17:00:00 9.000000 2016-04-17 17...,2016-04-17 17:00:00 757.000000 2016-04-17 1...,2016-04-17 17:00:00 65.0 2016-04-17 17:10:0...,2016-04-17 17:00:00 8.000000 2016-04-17 17:...,2016-04-17 17:00:00 40.0 2016-04-17 17:10:0...,2016-04-17 17:00:00 2.70 2016-04-17 17:10:0...,10.16

In [7]:
data[1]

KeyError: 1